"""The cabinet's starting screen: pick a game.

A list of titles down the left, a picture of the highlighted one on the right,
and that game's top three underneath. Up and down move, SELECT plays.

The picture is a still image file - `GameSpec.preview_image`, by convention
`games/<id>/preview.png`. It is loaded on first sight and scaled to the panel
once, so sitting on this screen costs one blit a frame no matter how long an
idle cabinet is left on it. A game whose file is missing or unreadable gets its
name on a black panel rather than a broken box: the picker must still list a
game whose art did not ship.

Pac-Man's is generated by `tools/make_preview.py` from art the game already
owns. Most games will just draw one.

The board shown here is the highlighted game's own (`cabinet/leaderboard.py`);
moving the cursor moves the high scores with it. That is the whole point of
showing them here - every game's three names are readable from the front of the
machine without starting any of them.
"""

import os

import pygame

from .. import constants as C
from .hints import draw_hint, sound_hint

HEADER_Y = 12

# -- list ------------------------------------------------------------------
LIST_X = 8
LIST_WIDTH = 88
LIST_Y = 34
ROW_HEIGHT = 16
ROW_GAP = 4
ROW_PITCH = ROW_HEIGHT + ROW_GAP
LIST_LABEL_X = LIST_X + 6

# -- preview ---------------------------------------------------------------
PREVIEW_BORDER = 2
PREVIEW_X = 102
PREVIEW_Y = LIST_Y
PREVIEW_WIDTH = 116
PREVIEW_HEIGHT = 128

# The rect the game actually draws into. 112x124 is exactly half of Pac-Man's
# 224x248 maze, which is why the panel is this size and not a rounder number:
# an integer downscale keeps the preview's pixels lined up with the source art.
PREVIEW_INNER = pygame.Rect(
    PREVIEW_X + PREVIEW_BORDER, PREVIEW_Y + PREVIEW_BORDER,
    PREVIEW_WIDTH - PREVIEW_BORDER * 2, PREVIEW_HEIGHT - PREVIEW_BORDER * 2,
)

# How many rows fit beside the preview before the list has to scroll.
VISIBLE_ROWS = max(1, (PREVIEW_HEIGHT + ROW_GAP) // ROW_PITCH)
# What a row can show at a 6px cell, less the cursor column and both margins.
MAX_LABEL_CHARS = (LIST_WIDTH - (LIST_LABEL_X - LIST_X) - 4) // 6

# -- detail panel ----------------------------------------------------------
PANEL_X = 8
PANEL_Y = 172
PANEL_WIDTH = C.LOGICAL_WIDTH - PANEL_X * 2      # 208
PANEL_HEIGHT = 80
PANEL_BORDER = 2

TITLE_Y = PANEL_Y + 8
TAGLINE_Y = PANEL_Y + 20
SCORES_Y = PANEL_Y + 38
SCORE_ROW_SPACING = 14

RANK_X = PANEL_X + 14
NAME_X = PANEL_X + 46
SCORE_RIGHT = PANEL_X + PANEL_WIDTH - 14

HINT_Y = C.LOGICAL_HEIGHT - 20

# Two hints, spaced as they are on a game's own title screen.
SEPARATOR = '   '

# `font.render` upper-cases its input, so these have to be glyphs of their own
# rather than '^' and 'v' - see `cabinet/font.py`.
ARROW_UP = '▲'
ARROW_DOWN = '▼'


class GameSelect:
    """The picker's state, drawing and input handling.

    `leaderboard_for(spec)` returns that game's board. It is a callable rather
    than a dict so the shell can keep one `Leaderboard` per game and hand the
    same instance to both this screen and the game itself.
    """

    def __init__(self, renderer, font, specs, leaderboard_for, controls=None,
                 sound_manager=None):
        self.renderer = renderer
        self.font = font
        self.specs = tuple(specs)
        self.leaderboard_for = leaderboard_for
        # Held by reference - the operator menu can change the scheme while
        # this screen is up, and the next frame must say the new thing.
        self.controls = controls
        # Only read for the speaker's mute state; this screen plays nothing.
        self.sound_manager = sound_manager

        self.index = 0
        self.scroll = 0
        self.scores = []
        # game id -> fitted Surface, or None for one that could not be loaded.
        self._previews = {}

        self.on_choose = None
        self.refresh()

    # -- state ---------------------------------------------------------------

    @property
    def scheme(self):
        return self.controls.scheme if self.controls else None

    @property
    def selected(self):
        """The highlighted spec, or None if no game is registered."""
        return self.specs[self.index] if self.specs else None

    @property
    def max_scroll(self):
        return max(0, len(self.specs) - VISIBLE_ROWS)

    def refresh(self):
        """Re-reads the highlighted game's board.

        Called on every selection change and by the shell after a reset or a
        saved name, which is this screen's equivalent of the reference's
        `leaderboardUpdated` listener.
        """
        spec = self.selected
        self.scores = self.leaderboard_for(spec).get_top_scores() if spec else []

    # -- input ---------------------------------------------------------------

    def move(self, delta):
        if not self.specs:
            return

        # Wraps, like the operator menu: on a mat, stepping off the end of a
        # short list and having to walk all the way back is worse than the
        # small surprise of wrapping.
        self.index = (self.index + delta) % len(self.specs)

        # Keep the cursor inside the visible window.
        if self.index < self.scroll:
            self.scroll = self.index
        elif self.index >= self.scroll + VISIBLE_ROWS:
            self.scroll = self.index - VISIBLE_ROWS + 1
        self.scroll = max(0, min(self.scroll, self.max_scroll))

        self.refresh()

    def handle_action(self, action):
        if action == 'up':
            self.move(-1)
        elif action == 'down':
            self.move(1)
        elif action == 'select':
            self.choose()

    def choose(self):
        spec = self.selected
        if spec is not None and self.on_choose:
            self.on_choose(spec)

    # -- drawing -------------------------------------------------------------

    def draw(self):
        # The shell has already cleared the frame - see `cabinet/app.py`.
        # Nothing on this screen animates, so it takes no clock.
        surface = self.renderer.surface

        self.font.draw(surface, 'SELECT GAME', C.LOGICAL_WIDTH / 2, HEADER_Y,
                       C.ARCADE_YELLOW, align='center')

        self.draw_list(surface)
        self.draw_preview(surface)
        self.draw_panel(surface)
        self.draw_hint(surface)

    def draw_list(self, surface):
        """One row per game, highlighted like the operator menu's rows."""
        window = self.specs[self.scroll:self.scroll + VISIBLE_ROWS]

        for row, spec in enumerate(window):
            y = LIST_Y + row * ROW_PITCH
            selected = (self.scroll + row) == self.index

            self.renderer.fill_rect_at(
                LIST_X, y, LIST_WIDTH, ROW_HEIGHT,
                C.ARCADE_YELLOW if selected else C.ARCADE_DARK,
            )
            self.font.draw(
                surface, spec.title[:MAX_LABEL_CHARS], LIST_LABEL_X,
                y + (ROW_HEIGHT - 7) / 2,
                C.ARCADE_DARK if selected else C.WHITE,
            )

        # Only drawn when the list is actually longer than the window, so a
        # cabinet with two games has no furniture it does not need.
        if self.max_scroll:
            self.draw_scroll_arrows(surface)

    def draw_scroll_arrows(self, surface):
        top = LIST_Y - 8
        bottom = LIST_Y + VISIBLE_ROWS * ROW_PITCH - ROW_GAP + 1

        if self.scroll > 0:
            self.font.draw(surface, ARROW_UP, LIST_X + LIST_WIDTH / 2, top,
                           C.ARCADE_GREY, align='center')
        if self.scroll < self.max_scroll:
            self.font.draw(surface, ARROW_DOWN, LIST_X + LIST_WIDTH / 2, bottom,
                           C.ARCADE_GREY, align='center')

    def preview_surface(self, spec):
        """The spec's picture, loaded and fitted to the panel once, or None.

        Cached per game, including the failures: a missing file must not mean
        a `pygame.image.load` attempt - and a disk hit - on every frame the
        cursor sits on that row.
        """
        if spec.id in self._previews:
            return self._previews[spec.id]

        surface = self._load_preview(spec)
        self._previews[spec.id] = surface
        return surface

    def _load_preview(self, spec):
        path = getattr(spec, 'preview_image', None)
        if not path or not os.path.exists(path):
            return None

        try:
            image = pygame.image.load(path)
        except pygame.error:
            # Same rule as everywhere else on this machine: a bad file is a
            # fallback, never a crash. The cabinet has to boot.
            return None

        # Blitting an unconverted surface is one of the few genuinely slow
        # things you can do in pygame. Conditional because `convert_alpha`
        # needs a display mode, and the tests draw onto a plain Surface.
        if pygame.display.get_surface() is not None:
            image = image.convert_alpha()

        # An image authored at the panel's exact size - which is what
        # `tools/make_preview.py` writes - is then blitted untouched. Pixel art
        # survives an integer downscale and very little else, so anything that
        # does need fitting is at least kept square rather than stretched.
        width, height = image.get_size()
        if not width or not height:
            return None

        scale = min(PREVIEW_INNER.width / width, PREVIEW_INNER.height / height)
        if scale != 1:
            image = pygame.transform.scale(
                image, (max(1, round(width * scale)),
                        max(1, round(height * scale))),
            )

        return image

    def draw_preview(self, surface):
        self.renderer.fill_rect_at(
            PREVIEW_X, PREVIEW_Y, PREVIEW_WIDTH, PREVIEW_HEIGHT, C.MAZE_BLUE,
        )
        self.renderer.fill_rect_at(
            PREVIEW_INNER.x, PREVIEW_INNER.y,
            PREVIEW_INNER.width, PREVIEW_INNER.height, C.BLACK,
        )

        spec = self.selected
        if spec is None:
            return

        image = self.preview_surface(spec)
        if image is None:
            self.font.draw(
                surface, spec.title, PREVIEW_INNER.centerx,
                PREVIEW_INNER.centery - 3, C.ARCADE_GREY, align='center',
            )
            return

        # Centred, so an image that is not the panel's shape is letterboxed
        # inside the border rather than pinned to a corner.
        surface.blit(image, image.get_rect(center=PREVIEW_INNER.center))

    def draw_panel(self, surface):
        self.renderer.fill_rect_at(
            PANEL_X - PANEL_BORDER, PANEL_Y - PANEL_BORDER,
            PANEL_WIDTH + PANEL_BORDER * 2, PANEL_HEIGHT + PANEL_BORDER * 2,
            C.MAZE_BLUE,
        )
        self.renderer.fill_rect_at(
            PANEL_X, PANEL_Y, PANEL_WIDTH, PANEL_HEIGHT, C.BLACK,
        )

        spec = self.selected
        center = PANEL_X + PANEL_WIDTH / 2

        if spec is None:
            # Not reachable with a registry that has entries, but a cabinet
            # whose registry is empty should say so rather than show an empty
            # box that reads as a failed read.
            self.font.draw(surface, 'NO GAMES INSTALLED', center, SCORES_Y,
                           C.ARCADE_RED, align='center')
            return

        self.font.draw(surface, spec.title, center, TITLE_Y,
                       C.ARCADE_YELLOW, align='center')
        if spec.tagline:
            self.font.draw(surface, spec.tagline, center, TAGLINE_Y,
                           C.ARCADE_GREY, align='center')

        for rank, label in enumerate(C.RANK_LABELS):
            y = SCORES_Y + rank * SCORE_ROW_SPACING
            entry = self.scores[rank] if rank < len(self.scores) else None

            self.font.draw(surface, label, RANK_X, y, C.ARCADE_CYAN)
            self.font.draw(surface, entry['name'] if entry else '---',
                           NAME_X, y, C.WHITE)
            self.font.draw(
                surface, str(int(entry['score'])) if entry else '00',
                SCORE_RIGHT, y, C.ARCADE_YELLOW, align='right',
            )

    def draw_hint(self, surface):
        scheme = self.scheme
        if scheme is None:
            return

        muted = (self.sound_manager is not None
                 and self.sound_manager.master_volume == 0)
        # The speaker rides along as a status light, exactly as it does on a
        # game's title screen: an operator looking at a silent cabinet needs to
        # know whether it is muted or broken before starting anything.
        draw_hint(
            surface, self.font,
            f'{scheme.menu_pick} PLAYS{SEPARATOR}{sound_hint(scheme)}',
            C.LOGICAL_WIDTH / 2, HINT_Y, C.ARCADE_GREY, align='center',
            muted=muted,
        )
